apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-bindings-controller-argo-clusterrole
rules:
- apiGroups:
  - "argoproj.io"
  resources:
  - rollouts
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: services-bindings-controller-argo-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: services-bindings-controller-argo-clusterrole
subjects:
- kind: ServiceAccount
  name: controller
  namespace: service-bindings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: dev
rules:
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev