apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: advanced-deployment-strategy-knative
spec:
spec:
  params:
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: ""
    name: gitops_ssh_secret
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: deliverable
    params:
    - name: registry
      value:
        repository: tap-wkld
        server: harbor.emea.end2end.link
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  - name: image-builder
    params:
    - name: serviceAccount
      value: default
    - name: clusterBuilder
      value: default
    - name: registry
      value:
        repository: tap-wkld
        server: harbor.emea.end2end.link
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-template
  - images:
    - name: image
      resource: image-builder
    name: config-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: revision-config-provider
    templateRef:
      kind: ClusterConfigTemplate
      name: revision-config-template-knative
  - configs:
    - name: revisionconfig
      resource: revision-config-provider
    - name: specconfig
      resource: config-provider 
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: config-template-knative
    params:
    - name: ingress_domain
      value: emea.end2end.link
  - configs:
    - name: config
      resource: app-config
    name: config-writer
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        repository: tap-wkld
        server: harbor.emea.end2end.link
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  selector:
    apps.tanzu.vmware.com/workload-type: web
    timosalm.de/advanced-deployment-strategy: "true"
    timosalm.de/advanced-deployment-strategy-impl: "knative"